version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: docker_compose_nginx
    environment: 
        - env_key=env_value
    ports: 
        - "8989:80"
    volumes:
        - ${PWD}:/usr/share/nginx/html:ro

  ubuntu:
    image: ubuntu:latest
    container_name: docker_compose_ubuntu
    command: ["sleep", "1500"]
    ports: 
        - "8999:80"

  busybox:
    image: busybox
    container_name: docker_compose_busy
    command: ["sleep", "1500"]