version: '3'

services:
  app:
    build:
      context: ./docker
    volumes:
      - ./my-laravel:/var/www/my-laravel
    ports:
      - "8080:80"
    working_dir: /var/www/my-laravel
    environment: 
      APACHE_DOCUMENT_ROOT: /var/www/my-laravel/public
      TZ: "Asia/Tokyo"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"